<fieldset class="fieldset field-age">
    <div class="field field-name-age required">
        <label class="label" for="age"><?= $block->escapeHtml(__('Your age')) ?></label>
        <div class="control">
            <input type="text" name="age" id="age" value="<?= $block->getCustomer()->getCustomAttribute('age')->getValue(); ?>" title="<?= $block->escapeHtmlAttr(__('Your age')) ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
</fieldset>